### PR TITLE
Dev property

### LINKED ISSUE #1264: Need a way to record the valuetype for pattern matching in a dictionary
Here's a case where our default `valuetype  = "glob"` assumption would be broken:

```r
data(data_dictionary_HuLiu, package = "quanteda.dictionaries")
data_char_HuLiu <- unlist(as.list(data_dictionary_HuLiu))

# detect what could appear to be a glob pattern
asterisks_index <- stringi::stri_detect_fixed(data_char_HuLiu, "*")
data_char_HuLiu[asterisks_index]
## negative468  negative811 negative1560 negative3765 
##  "bull****"       "d*mn"       "f**k"       "sh*t"

# but it's a literal
damn_index <- stringi::stri_detect_regex(data_char_HuLiu, "^d.*mn")
data_char_HuLiu[damn_index]
## negative811 negative816 negative817 negative818 negative819 negative820 negative821 
##      "d*mn"      "damn"  "damnable"  "damnably" "damnation"    "damned"   "damning" 
```

### Solution

Record this a slot called `@valuetype`. This will be the default for matching on a dictionary unless the user overrides it by specifying an explicit `valuetype` for any matching operation.

### PR DESCRIPTION
**Pull request by koheiw**
Add `meta$object` to record object-related information for #1845. Main changes are 
- `build_*` and `rebuild_*` functions that mimic S4's `new()` method
- Related internal functions to handle the meta attribute
- Functions that require `concatenator` and `ngram` values.
- Improve consistency in how functions are written.

Solves #1845 
Solves #1828 
Closes #1264

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -134,23 +134,25 @@ pattern2list <- function(pattern, types, valuetype, case_insensitive,
         }
         attr(result, "pattern") <- match(names(result), names(temp))
     } else {
-        if (length(pattern) == 0) return(list())
-        if (is.dictionary(pattern)) {
-            temp <- flatten_dictionary(pattern, levels)
+        if (length(x) == 0) return(list())
+        if (is.dictionary(x)) {
+            x <- as.dictionary(x)
+            attrs <- attributes(x)
```
Comment (kbenoit) [inline R/utils.R]: `attrs` is not used in this function

File: R/dfm_weight.R [hunk 2]
```diff
@@ -69,7 +73,7 @@ dfm_weight <- function(
     scheme = c("count", "prop", "propmax", "logcount", "boolean", "augmented", "logave"),
     weights = NULL,
     base = 10,
-    K = 0.5,
```
[the remark this answers is not in the document]
Comment (kbenoit) [reply R/dfm_weight.R]: I can live with this though - probably not many people will have ever used this parameter.

File: R/dfm_weight.R [hunk 3]
```diff
@@ -241,6 +241,23 @@ dfm_smooth.dfm <- function(x, smoothing = 1) {
 #' feature occurs more than a given frequency threshold.  (The default threshold
 #' is  zero, meaning that any feature occurring at least once in a document will
 #' be counted.)
+#' @param x a [dfm]
```
Comment (kbenoit) [inline R/dfm_weight.R]: I had to restore these because although the argument names are the same as in `dfm_weight()`, the documentation entries are different (except `threshold`).

**Comment by kbenoit** [comment]
This is ready to go IMO but first I'd like you to:
- check the unused variables queries above
- can you document the internal functions in meta.R a bit better?

File: R/corpus-methods-base.R [hunk 4]
```diff
@@ -193,24 +193,23 @@ tail.corpus <- function(x, n = 6L, ...) {
 `+.corpus` <- function(c1, c2) {
     c1 <- as.corpus(c1)
     c2 <- as.corpus(c2)
+    attrs1 <- attributes(c1)
+    attrs2 <- attributes(c2)
```
[the remark this answers is not in the document]
Comment (koheiw) [reply R/corpus-methods-base.R]: I wasn't entirely sure what to do with meta from `c2`. We can block combining corpora with different `unit`, attach user meta from `c1` and `c2`, etc.

File: R/dfm.R [hunk 5]
```diff
@@ -299,9 +322,11 @@ dfm.dfm <- function(x,
                     verbose = quanteda_options("verbose"),
                     ...) {
 
+    unused_dots(...)
+    
     x <- as.dfm(x)
     valuetype <- match.arg(valuetype)
-    check_dots(list(...))
+    attrs <- attributes(x)
```
[the remark this answers is not in the document]
Comment (koheiw) [reply R/dfm.R]: I will take this out.

File: R/docvars.R [hunk 6]
```diff
@@ -141,7 +141,9 @@ subset_docvars <- function(x, i = NULL) {
 }
 
 # Reshape docvars keeping variables that have the same values within groups
-group_docvars <- function(x, group) {
+group_docvars <- function(x, group = NULL) {
```
[the remark this answers is not in the document]
Comment (koheiw) [reply R/docvars.R]: Right. `docnum` is not longer used.

File: R/corpus-methods-base.R (hunk 4 above)
[the remark this answers is not in the document]
Comment (kbenoit) [reply R/corpus-methods-base.R]: not really sure what is best here, but for now, I'd say match previous behaviour.

File: R/utils.R (hunk 1 above)
Comment (koheiw) [reply R/utils.R]: Right.

File: R/tokens.R [hunk 7]
```diff
@@ -280,22 +280,9 @@ tokens.corpus <- function(x,
...
-            unlist(x, recursive = FALSE), 
-            types = attr(x[[length(x)]], "types"),
-            what = what, 
-            ngram = 1L, 
-            skip = 0L,
-            concatenator = "_",
-            docvars = docvars,
-            meta = attrs[["meta"]]
-    )
+    return(result)
```
Comment (koheiw) [inline R/tokens.R]: We have to use `build_tokens()` always to make sure that object has all the meta fields.

Comment (kbenoit) [reply R/tokens.R]: yes but the previous call to as.tokens() uses build_tokens()

File: R/meta.R [hunk 8]
```diff
@@ -115,44 +152,241 @@ check_valid_meta_object <- function(x) {
...
+        } else if (length(inherit) && m %in% names(inherit)) {
+            if (!identical(class(default[[m]]), class(inherit[[m]])))
+                stop("Invalid inherit object for ", m)
+            default[[m]] <- inherit[[m]]
+        }
+    }
+    return(default)
+}
+
+#' Internal functions to access meta filed in a list of attributes
```
[the remark this answers is not in the document]
Comment (koheiw) [reply R/meta.R]: Done

File: R/tokens.R [hunk 9]
```diff
@@ -248,9 +248,8 @@ tokens.corpus <- function(x,
     if ("remove_twitter" %in% names(dots)) {
         .Defunct(msg = "'remove_twitter' is defunct, use 'what = \"word2\"' instead.")
     }
-    unused_dots(dots)
+    check_dots(dots, c(names(formals(tokens))))
```
Comment (koheiw) [inline R/tokens.R]: I changed all the `check_dots()` to simpler `unused_dots()` in all the functions. We should choose either.

Comment (kbenoit) [reply R/tokens.R]: unused_dots() is fine, but I needed to be able to change (...) in the parent function (for trapping deprecated arguments) and then send the resulting (modified) list to the check_dots(). You cannot use list(...) in the child fn if it's already been evaluated - then it's a list one level deep. So just to get this branch working, for now, I added back the previous fn. But you are right we only should use one.

File: R/tokens.R (hunk 7 above)
Comment (kbenoit) [reply R/tokens.R]: but fix it as you need to, whatever gets it working for now, we can tidy up later.

**Comment by koheiw** [comment]
I noticed that the blocked serialization has been removed. We should restore this, otherwise it becomes impossible to tokenize lerge texts with limited RAM.
https://github.com/quanteda/quanteda/blob/40de44e973fdf7deccb769b0ff9e4900ff75f8c8/R/tokens.R#L453-L479

**Comment by kbenoit** [comment]
Makes sense, but let’s add it back as a separate fix after merging this monster. We can clean this up, get it merged, and then discuss the best place to batch the tokens construction.

**Comment by koheiw** [comment]
Done!
